import type { Metadata } from "next";
import { FileProvider } from "@/context/FileContext";
import { PasswordProvider } from "../context/PasswordContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-full flex flex-col">
        <FileProvider>
          <PasswordProvider>
            {children}
          </PasswordProvider>
        </FileProvider>
      </body>
    </html>
  );
}
